### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by GeorgeIoak** [aaronjsmith/stamps.com-php#1]
Thanks for saving me some time with the Stamps.com API. I was curious if you had experimented with any of the GetURL methods, specifically I was hoping to work with OnlineReportingHistory but I'm a little confused on how to access it.

**Comment by aaronjsmith** [comment]
`$this->functions = $this->client->__getFunctions();`
This will help you determine which functions you can access.

I am currently just working with the Get Rates functionality for the time being, I believe you may even be ahead of me, If you figure out a good solution feel free to post it here.
