### ISSUE TITLE
How to move to Production .

### ISSUE THREAD

**Issue by shellprog** [aaronjsmith/stamps.com-php#2]
Hi ,
Thanks for code , but i am concerned did stamps.com approved your implementation to be used in production environment , since in move to production document it is written 

AuthenticateUser
- After a user authenticates using AuthenticateUser, are you using the authenticator token in all subsequent requests during the session?

But in your implementation you are doing AuthenticateUser in all requests so did you used a different approach in production / stamps.com approved this without any issue / you didnt tested it in production environment ..

Thanks again for your valuable code
Imran

**Comment by aaronjsmith** [comment]
$this->Authenticator = $auth->Authenticator; has to be stored, so you don't necessarily have to authenticate again once you have the authentication stored.  I would find a way to store that value.

I believe you would have to create a new $auth->Authenticator for production .

**Comment by shellprog** [comment]
As  per production docs once you get the authenticator token you should save that in session and use it for all subsequent requests So below will work

```
if(Session::has('stamps_token')){
        $this->Authenticator = Session::get('stamps_token');
    }else{
        $auth = $this->client->AuthenticateUser($authData);
        $this->Authenticator = $auth->Authenticator;
        Session::put('stamps_token', $this->Authenticator);
    }
```
