### ISSUE TITLE
How to create USPS shipping labels from stamps.com

### ISSUE THREAD

**Issue by wdwtest** [aaronjsmith/stamps.com-php#3]
Hi,
Can you please explain or provide code for creating USPS shipping labels from stamps.com?

**Comment by aaronjsmith** [comment]
Use the following to get the API structure from the wsdl, you can then determine how you can get the shipping labels.
$stamps_com = new stamps_com;


print_r($stamps_com->client->__getFunctions());
print_r($stamps_com->client->__getTypes()); 

Here is a link to the stamps.com documentation: http://developer.stamps.com/assets/documents/developer/downloads/Stamps.com_XML_Format_Specs_v1.2.pdf
